name: Example Site Build

on:
  release:
    types: [published]

jobs:
  build-deploy:
    permissions:
     contents: write
     
    name: Build and Deploy
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.119.0"
          extended: true
          
      - name: Build
        working-directory: ./exampleSite
        run: hugo --minify --themesDir ../.. --baseURL https://chrede88.github.io/L1nkr/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./exampleSite/public
